name: smores_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  flutter_screenutil: ^0.6.0
  flutter:
    sdk: flutter
  intl: ^0.15.8
  provider: ^4.0.4
  image_picker: 0.6.3+4 
  path_provider: ^1.6.5
  cupertino_icons: ^0.1.3
  flutter_launcher_icons: "^0.7.2"
  flutter_easyloading: ^1.0.1
  bmprogresshud: ^0.0.5
  amazon_s3_cognito: '^0.2.3'
  dcdg: ^2.0.1
  font_awesome_flutter: ^8.5.0
  progress_dialog: ^1.2.0
  flutter_spinkit: ^4.1.2+1
  ff_navigation_bar: ^0.1.3
  analyzer: ^0.36.0
  json_serializable: ^3.1.0
  shared_preferences: ^0.5.6+3
  fluttertoast: ^4.0.1
  web_socket_channel: ^1.1.0
  cached_network_image: ^2.0.0
  flutter_aws_s3_client: ^0.5.0
  l10n: ^2.0.19
  percent_indicator: ^2.1.1+1
  flutter_swiper: ^1.1.6
  charts_flutter: ^0.9.0
  slider_button: ^0.5.0
  sleek_circular_slider : ^1.1.0
  awesome_button: ^1.0.2  
  rounded_loading_button: ^1.0.4
  fl_chart: ^0.9.0
  month_picker_strip: ^0.0.3
  random_color: ^1.0.5
  dropdown_formfield: ^0.1.2
  social_media_buttons: ^0.1.2
  flutter_nfc_reader: ^0.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: "launcher_icon"
  image_path: "assets/launcher/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/CustomIcons.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: assets/Poppins-Medium.ttf 


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
